---

- name: install jdk14
  command: bash -l -c "sdk install java 14.0.2-open"
  register: _sdk_install_result
  failed_when: "_sdk_install_result.rc != 0 and 'already installed' not in _sdk_install_result.stdout"
  changed_when: _sdk_install_result.rc != 0

- name: default jdk14
  command: bash -l -c "sdk default java 14.0.2-open"
  register: _sdk_install_result
  changed_when: false

- name: install maven
  command: bash -l -c "sdk install maven 3.6.3"
  register: _sdk_install_result
  failed_when: "_sdk_install_result.rc != 0 and 'already installed' not in _sdk_install_result.stdout"
  changed_when: _sdk_install_result.rc != 0

- name: default maven
  command: bash -l -c "sdk default maven 3.6.3"
  register: _sdk_install_result
  changed_when: false

...
