---
- hosts: localhost
  connection: local

  vars:
    - root: "{{ dx15_root | default(ansible_env.HOME) }}"
    - clean: "{{ dx15_clean | default(false) }}"
    - profile: home
    - emacs_font_height: 100
    - alacritty_font_size: 10
    - bash_path: /bin/bash

  pre_tasks:
    - name: create temporary directory
      tempfile:
        state: directory
      register: tempdir
      changed_when: false

  roles:
    - user

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"

  post_tasks:
    - name: remove temporary directory
      file:
        path: "{{ tempdir.path }}"
        state: absent
      changed_when: false
