---
- name: python -- install -- pipenv
  pacman:
    name: python-pipenv
    state: present

- name: python -- install -- pyenv
  pacman:
    name: pyenv
    state: present

- name: python -- install -- black
  pacman:
    name: python-black
    state: present

- name: python -- install -- poetry
  include_tasks: aur.yml
  vars:
    package: poetry

- name: Install documentation
  pacman:
    name:
      - python-docs
      - python2-docs
    state: present
