---
- name: Install GNOME Display Manager (GDM)
  become: true
  pacman:
    name: gdm
    state: present

- name: Enable GDM
  service: name=gdm.service enabled=yes

- name: Creating DConf configuration profile
  become: true
  copy: src=profile/gdm dest=/etc/dconf/profile/gdm

- name: Creating gdm.d directory for DConf
  become: true
  file: path=/etc/dconf/db/gdm.d state=directory mode=0755

- name: Configuring GDM
  become: true
  template: src=gdm.d/00-spark.j2 dest=/etc/dconf/db/gdm.d/00-spark
  notify: update DConf database
