---
- name: Install xdg-user-dirs
  become: true
  pacman: name=xdg-user-dirs state=present
  tags:
    - xdg

- name: Create user directories
  command: /usr/bin/xdg-user-dirs-update
  become: yes
  # become_user: "{{ user.name }}"
  tags:
    - xdg

- name: Install perl-file-mimeinfo
  become: true
  pacman: name=perl-file-mimeinfo state=present
  tags:
    - xdg
