---

- name: docker -- install packages
  become: true
  package:
    name: [docker, docker-compose]

- name: docker -- enable/start
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

...
