---
- name: corepkgs -- install packages
  become: true
  package:
    name:
      - base-devel
      - man-db
      - man-pages
      - pacman-contrib
      - fwupd
      - dmidecode
      - tmux
      - git
      - rsync
      - coreutils
      - moreutils
      - dateutils
      - bc
      - ranger
      - arch-wiki-lite
      - arch-wiki-docs
      - python-keyring
      - python-secretstorage
      - tig
      - pv
      - minicom
      - jq
      - screen
      - termdown
      - fzf
      - cpulimit
      - fakeroot
      - binutils
      - xorg-server
      - xorg-apps
      - xorg-drivers
      - netctl
      - ifplugd
      - dialog
      - sudo
      - tar
      - gzip
      - clang
      - unzip
