---

- name: swap -- install packages
  become: true
  package:
    name: systemd-swap

- name: swap -- create swap file
  become: true
  command: "dd if=/dev/zero of=/var/local/swapf0 bs=1M count={{ ansible_memtotal_mb * 2 }}"
  args:
    creates: /var/local/swapf0

- name: swap -- swaplabel
  become: true
  command: swaplabel /var/local/swapf0
  failed_when: "swaplabel.rc not in [0, 1]"
  changed_when: false
  register: swaplabel

- name: swap -- mkswap
  become: true
  command: mkswap /var/local/swapf0
  when: swaplabel.rc != 0

- name: swap -- configure fstab
  become: true
  lineinfile:
    path: /etc/fstab
    line: "/var/local/swapf0 none swap defaults 0 0"
    insertafter: EOF

- name: swap -- configure zram
  become: true
  copy:
    src: zram.conf
    dest: /etc/systemd/swap.conf.d/zram.conf

- name: swap -- enable/start
  become: true
  systemd:
    name: systemd-swap
    state: started
    enabled: true
