---

- name: sysctl -- unprivileged clones
  become: true
  sysctl:
    name: kernel.unprivileged_userns_clone
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/kernel_unprivileged_userns_clone.conf

...
