---

- name: install packages
  become: true
  package:
    name: [alacritty, tmux]

- name: alacritty config directory
  file:
    path: "{{ root }}/.config/alacritty"
    state: directory

- name: alacritty config file
  template:
    src: alacritty.yml
    dest: "{{ root }}/.config/alacritty/alacritty.yml"

- name: tmux config file
  template:
    src: .tmux.conf
    dest: "{{ root }}/.tmux.conf"

...
